### Week2授業前課題3  行列積のスクラッチ

In [1]:
'''
モジュールのインポート
'''
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

#### 【問題1】行列積を手計算する

In [76]:
'''
行列A、Bの行列積を手計算で解くコード
計算過程もマークダウンテキストを用いて説明
'''
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

a_row = a_ndarray.shape[0]  # a_ndarra　の行数を取得
a_col = a_ndarray.shape[1]   # a_ndarra の列数を取得
b_row = b_ndarray.shape[0] # b_ndarra　の行数を取得
b_col = b_ndarray.shape[1]  # b_ndarra の列数を取得
c_ndarray = np.array([])


for i in range(a_row):
    for j in range(b_col):
        temp = np.array([])
        for k in range(b_row):
            temp = np.append(temp, a_ndarray[i][k] * b_ndarray[k][j])
        c_ndarray = np.append(c_ndarray, np.sum(temp))
c_ndarray = np.reshape(c_ndarray, (a_row, b_col))

print(c_ndarray)
print(c_ndarray.shape)

[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]
(3, 3)


- 計算過程の説明
    - for 構文で使うため、各行列の形状を求める
    - for 構文内にて、i = a_ndarray の行、j = b_ndarray の列、k = b_ndarray の行 で繰り返す回数を指定

#### 【問題2】NumPyの関数による計算

In [80]:
'''
np.matmul()やnp.dot()、または@演算子を使った計算コード
'''
print(np.dot(a_ndarray, b_ndarray))
print(np.matmul(a_ndarray, b_ndarray))
print(a_ndarray @ b_ndarray)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


#### 【問題3】ある要素の計算を実装

In [95]:
'''
手計算にて行列A の０行目、行列B の０列目を計算するコード
'''
temp = np.array([])
c_ndarray = np.array([])

# 行列A の０行目、行列B の０列目における処理
for j in range(b_row):
    temp = np.append(temp, a_ndarray[0][j] * b_ndarray[j][0])
c_ndarray = np.append(c_ndarray, np.sum(temp))
print(c_ndarray)

[6.]


#### 【問題4】行列積を行う関数の作成

In [113]:
'''
行列A、B のを引数に受け取り、行列積を返す関数を作成するコード
'''
matrix_a = np.random.randint(0, 10, size=(3, 3))
matrix_b = np.random.randint(0, 10, size=(3, 3))

def matrix_multi(matrix_a, matrix_b):
    matrix_a_row = a_ndarray.shape[0]
    matrix_a_col = a_ndarray.shape[1]
    matrix_b_row = b_ndarray.shape[0]
    matirx_b_col = b_ndarray.shape[1]
    matrix_c = np.array([])

    for i in range(matrix_a_row):
        for j in range(matrix_b_col):
            temp = np.array([])
            for k in range(matrix_b_row):
                temp = np.append(temp, matrix_a[i][k] * matrix_b[k][j])
            matrix_c = np.append(matrix_c, np.sum(temp))
    matrix_c = np.reshape(matrix_c, (matrix_a_row, matrix_b_col))
    return matrix_c

matrix_c = matrix_multi(matrix_a, matrix_b)
print(matrix_c)

[[149. 159. 108.]
 [ 68.  77.  52.]
 [ 25.  37.  24.]]


【問題5】計算が定義されない入力を判定する

In [128]:
'''
問題４にエラー対応を加えたコード
'''
matrix_a = np.random.randint(0, 10, size=(3, 3))
matrix_b = np.random.randint(0, 10, size=(5, 3))

def matrix_multi(matrix_a, matrix_b):
    matrix_a_row = matrix_a.shape[0]
    matrix_a_col = matrix_a.shape[1]
    matrix_b_row = matrix_b.shape[0]
    matirx_b_col = matrix_b.shape[1]
    matrix_c = np.array([])

    if matrix_a_col == matrix_b_row:
        for i in range(matrix_a_row):
            for j in range(matrix_b_col):
                temp = np.array([])
                for k in range(matrix_b_row):
                    temp = np.append(temp, matrix_a[i][k] * matrix_b[k][j])
                matrix_c = np.append(matrix_c, np.sum(temp))
        matrix_c = np.reshape(matrix_c, (matrix_a_row, matrix_b_col))
        return matrix_c
    print("二つの行列のうち行数と列数が一致しません")

matrix_c = matrix_multi(matrix_a, matrix_b)
print(matrix_c)

二つの行列のうち行数と列数が一致しません
None


#### 【問題6】転置

In [151]:
'''
片方の行列を転置することで、行列積が計算するコード
'''
# 2次元配列
two_dimension_a = np.random.randint(0, 10, size=(4, 2))
print("2次元配列")
print("配列：\n{}".format(two_dimension_a))
print("転置：\n{}".format(two_dimension_a.T))
print("行列積：\n{}".format(np.dot(two_dimension_a.T, two_dimension_a)))
print("配列(transpose(0, 1))：\n{}".format(two_dimension_a.transpose(0, 1)))
print("配列(transpose(1, 0))：\n{}".format(two_dimension_a.transpose(1, 0)))
print("行列積(transpose)：\n{}".format(np.dot(two_dimension_a.transpose(1, 0), two_dimension_a.transpose(0, 1))))

2次元配列
配列：
[[8 9]
 [7 1]
 [1 2]
 [6 3]]
転置：
[[8 7 1 6]
 [9 1 2 3]]
行列積：
[[150  99]
 [ 99  95]]
配列(transpose(0, 1))：
[[8 9]
 [7 1]
 [1 2]
 [6 3]]
配列(transpose(1, 0))：
[[8 7 1 6]
 [9 1 2 3]]
行列積(transpose)：
[[150  99]
 [ 99  95]]
